# Generated by Django 2.0.8 on 2018-09-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_auto_20180903_1809'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(through='teams.TeamSeason', to='nfl.Season'),
        ),
    ]
