# Generated by Django 2.0.8 on 2018-09-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20180903_1809'),
        ('nfl', '0004_auto_20180903_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.NFLGame')),
                ('picked_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.NFLTeam')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
