# Generated by Django 2.0.8 on 2018-12-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20181215_1942'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leagues',
            field=models.ManyToManyField(to='leagues.League'),
        ),
    ]
