# Generated by Django 2.0.8 on 2018-12-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_leagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leagues',
        ),
    ]
