# Generated by Django 2.0.8 on 2018-09-03 04:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_wrong_picks', models.IntegerField(default=2)),
                ('max_times_a_team_can_be_picked', models.SmallIntegerField(default=2)),
                ('latest_pick_accepted_day', models.SmallIntegerField(choices=[(0, 'Friday'), (1, 'Saturday'), (2, 'Sunday')], default=2)),
                ('latest_pick_accepted_time', models.TimeField(default=datetime.time(9, 0))),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leaguerules',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.Season'),
        ),
    ]
