# Generated by Django 2.0.8 on 2018-09-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('nfl', '0004_auto_20180903_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerules',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.Season'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
