# Generated by Django 2.0.8 on 2018-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20180903_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
