# Generated by Django 2.0.8 on 2018-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20180903_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
