# Generated by Django 2.0.8 on 2018-09-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20180903_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='password',
            new_name='passphrase',
        ),
    ]
