# Generated by Django 2.0.8 on 2018-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20180903_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=True),
        ),
    ]
