# Generated by Django 2.0.8 on 2018-12-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20180903_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerules',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='leagues.League'),
        ),
    ]
