# Generated by Django 2.0.8 on 2018-12-16 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0008_auto_20181215_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_league', to=settings.AUTH_USER_MODEL),
        ),
    ]
