# Generated by Django 2.0.8 on 2018-08-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NFLDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='nfl.NFLConference')),
            ],
        ),
        migrations.CreateModel(
            name='NFLGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.IntegerField()),
                ('week', models.IntegerField()),
                ('scheduled_start_time', models.DateTimeField()),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('season', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='nfl.NFLDivision')),
            ],
        ),
        migrations.AddField(
            model_name='nflgame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='nfl.NFLTeam'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='nfl.NFLTeam'),
        ),
    ]
