# Generated by Django 2.0.8 on 2018-08-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflconference',
            options={'verbose_name': 'NFL Conference', 'verbose_name_plural': 'NFL Conferences'},
        ),
        migrations.AlterModelOptions(
            name='nfldivision',
            options={'verbose_name': 'NFL Division', 'verbose_name_plural': 'NFL Divisions'},
        ),
        migrations.AlterModelOptions(
            name='nflgame',
            options={'verbose_name': 'NFL Game', 'verbose_name_plural': 'NFL Games'},
        ),
        migrations.AlterModelOptions(
            name='nflteam',
            options={'verbose_name': 'NFL Team', 'verbose_name_plural': 'NFL Teams'},
        ),
        migrations.RemoveField(
            model_name='nflteam',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='nflteam',
            name='season',
        ),
    ]
