# Generated by Django 2.0.8 on 2018-08-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_auto_20180820_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflteam',
            options={'ordering': ['region', 'nickname'], 'verbose_name': 'NFL Team', 'verbose_name_plural': 'NFL Teams'},
        ),
    ]
