# Generated by Django 2.0.8 on 2018-09-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_auto_20180826_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season_start_date', models.DateTimeField()),
                ('season_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.Season')),
            ],
        ),
        migrations.RemoveField(
            model_name='nflgame',
            name='season_type',
        ),
        migrations.AddField(
            model_name='nflteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfl.Week'),
        ),
    ]
