# Generated by Django 2.0.8 on 2018-09-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_auto_20180903_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nfl.Season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_start_date',
            field=models.DateField(),
        ),
    ]
