# Generated by Django 2.0.8 on 2018-09-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_auto_20180903_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
